services:
  db:
      image: postgres:14-alpine
      ports:
        - 5432:5432
      volumes:
       - postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=mydb

  # Back-end Nest App
  frontend:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nx/cache # Montez le cache pour qu'il soit partagé et mis à jour correctement
    command: sh -c "npm install && npm run front:dev:docker"
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # Back-end Nest App
  backend:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - /app/.nx/cache # Montez le cache pour qu'il soit partagé et mis à jour correctement
    command: sh -c "npm install && npm run back:dev:docker"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db

volumes:
  postgres_data:
