services:
  # Database - Postgres
  db:
    container_name: batsupport-db
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb

  # Vue App
  app:
    container_name: batsupport-app
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run app:dev:docker
    ports:
      - 4200:4200

  # Nest App
  api:
    container_name: batsupport-api
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    volumes:
      - /app/.nx/cache
    command: "npm run api:dev:docker"
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mono-node-modules: null
  postgres_data: null
